const db = require("../models");

const priceCase = db.PriceCase;

module.exports = {
    seedpriceCases : function () {        
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'comme_neuf', simBlocked: 1, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'comme_neuf', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'comme_neuf', simBlocked: 1, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'comme_neuf', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'comme_neuf', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'comme_neuf', simBlocked: 0, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'bonne_état', simBlocked: 1, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'bonne_état', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'bonne_état', simBlocked: 1, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'bonne_état', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'bonne_état', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'bonne_état', simBlocked: 0, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'abimé', simBlocked: 1, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'abimé', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'abimé', simBlocked: 1, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'abimé', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'abimé', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'abimé', simBlocked: 0, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'cassé', simBlocked: 1, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'cassé', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'cassé', simBlocked: 1, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'cassé', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'cassé', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'comme_neuf', state_screen: 'cassé', simBlocked: 0, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'comme_neuf', simBlocked: 1, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'comme_neuf', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'comme_neuf', simBlocked: 1, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'comme_neuf', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'comme_neuf', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'comme_neuf', simBlocked: 0, storage: 64 } , price: 10 });
            priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'bonne_état', simBlocked: 1, storage: 16 } , price: 10 });
            priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'bonne_état', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'bonne_état', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'bonne_état', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'bonne_état', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'bonne_état', simBlocked: 0, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'abimé', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'abimé', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'abimé', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'abimé', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'abimé', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'abimé', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'cassé', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'cassé', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'cassé', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'cassé', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'cassé', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'bonne_état', state_screen: 'cassé', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'comme_neuf', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'comme_neuf', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'comme_neuf', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'comme_neuf', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'comme_neuf', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'comme_neuf', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'bonne_état', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'bonne_état', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'bonne_état', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'bonne_état', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'bonne_état', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'bonne_état', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'abimé', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'abimé', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'abimé', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'abimé', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'abimé', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'abimé', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'cassé', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'cassé', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'cassé', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'cassé', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'cassé', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'abimé', state_screen: 'cassé', simBlocked: 0, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'comme_neuf', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'comme_neuf', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'comme_neuf', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'comme_neuf', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'comme_neuf', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'comme_neuf', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'bonne_état', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'bonne_état', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'bonne_état', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'bonne_état', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'bonne_état', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'bonne_état', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'abimé', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'abimé', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'abimé', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'abimé', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'abimé', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'abimé', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'cassé', simBlocked: 1, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'cassé', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'cassé', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'cassé', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'cassé', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1428" ,state: { state_body: 'cassé', state_screen: 'cassé', simBlocked: 0, storage: 64 } , price: 10 });

        // ---------------------------- 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'comme_neuf', simBlocked: 1, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'comme_neuf', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'comme_neuf', simBlocked: 1, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'comme_neuf', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'comme_neuf', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'comme_neuf', simBlocked: 0, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'bonne_état', simBlocked: 1, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'bonne_état', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'bonne_état', simBlocked: 1, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'bonne_état', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'bonne_état', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'bonne_état', simBlocked: 0, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'abimé', simBlocked: 1, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'abimé', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'abimé', simBlocked: 1, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'abimé', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'abimé', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'abimé', simBlocked: 0, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'cassé', simBlocked: 1, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'cassé', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'cassé', simBlocked: 1, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'cassé', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'cassé', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'comme_neuf', state_screen: 'cassé', simBlocked: 0, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'comme_neuf', simBlocked: 1, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'comme_neuf', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'comme_neuf', simBlocked: 1, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'comme_neuf', simBlocked: 0, storage: 16 } , price: 10 });
         priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'comme_neuf', simBlocked: 0, storage: 32 } , price: 10 }); 
         priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'comme_neuf', simBlocked: 0, storage: 64 } , price: 10 });
          priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'bonne_état', simBlocked: 1, storage: 16 } , price: 10 });
           priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'bonne_état', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'bonne_état', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'bonne_état', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'bonne_état', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'bonne_état', simBlocked: 0, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'abimé', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'abimé', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'abimé', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'abimé', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'abimé', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'abimé', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'cassé', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'cassé', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'cassé', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'cassé', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'cassé', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'bonne_état', state_screen: 'cassé', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'comme_neuf', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'comme_neuf', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'comme_neuf', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'comme_neuf', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'comme_neuf', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'comme_neuf', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'bonne_état', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'bonne_état', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'bonne_état', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'bonne_état', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'bonne_état', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'bonne_état', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'abimé', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'abimé', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'abimé', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'abimé', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'abimé', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'abimé', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'cassé', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'cassé', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'cassé', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'cassé', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'cassé', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'abimé', state_screen: 'cassé', simBlocked: 0, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'comme_neuf', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'comme_neuf', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'comme_neuf', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'comme_neuf', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'comme_neuf', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'comme_neuf', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'bonne_état', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'bonne_état', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'bonne_état', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'bonne_état', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'bonne_état', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'bonne_état', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'abimé', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'abimé', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'abimé', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'abimé', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'abimé', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'abimé', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'cassé', simBlocked: 1, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'cassé', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'cassé', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'cassé', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'cassé', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1507" , state : {state_body: 'cassé', state_screen: 'cassé', simBlocked: 0, storage: 64 } , price: 10 }); 

        //-----

        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'comme_neuf', simBlocked: 1, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'comme_neuf', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'comme_neuf', simBlocked: 1, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'comme_neuf', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'comme_neuf', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'comme_neuf', simBlocked: 0, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'bonne_état', simBlocked: 1, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'bonne_état', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'bonne_état', simBlocked: 1, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'bonne_état', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'bonne_état', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'bonne_état', simBlocked: 0, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'abimé', simBlocked: 1, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'abimé', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'abimé', simBlocked: 1, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'abimé', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'abimé', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'abimé', simBlocked: 0, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'cassé', simBlocked: 1, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'cassé', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'cassé', simBlocked: 1, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'cassé', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'cassé', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'comme_neuf', state_screen: 'cassé', simBlocked: 0, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'comme_neuf', simBlocked: 1, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'comme_neuf', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'comme_neuf', simBlocked: 1, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'comme_neuf', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'comme_neuf', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'comme_neuf', simBlocked: 0, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'bonne_état', simBlocked: 1, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'bonne_état', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'bonne_état', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'bonne_état', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'bonne_état', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'bonne_état', simBlocked: 0, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'abimé', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'abimé', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'abimé', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'abimé', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'abimé', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'abimé', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'cassé', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'cassé', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'cassé', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'cassé', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'cassé', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'bonne_état', state_screen: 'cassé', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'comme_neuf', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'comme_neuf', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'comme_neuf', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'comme_neuf', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'comme_neuf', simBlocked: 0, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'comme_neuf', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'bonne_état', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'bonne_état', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'bonne_état', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'bonne_état', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'bonne_état', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'bonne_état', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'abimé', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'abimé', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'abimé', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'abimé', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'abimé', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'abimé', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'cassé', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'cassé', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'cassé', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'cassé', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'cassé', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'abimé', state_screen: 'cassé', simBlocked: 0, storage: 64 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'comme_neuf', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'comme_neuf', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'comme_neuf', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'comme_neuf', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'comme_neuf', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'comme_neuf', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'bonne_état', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'bonne_état', simBlocked: 1, storage: 32 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'bonne_état', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'bonne_état', simBlocked: 0, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'bonne_état', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'bonne_état', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'abimé', simBlocked: 1, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'abimé', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'abimé', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'abimé', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'abimé', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'abimé', simBlocked: 0, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'cassé', simBlocked: 1, storage: 16 } , price: 10 });
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'cassé', simBlocked: 1, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'cassé', simBlocked: 1, storage: 64 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'cassé', simBlocked: 0, storage: 16 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'cassé', simBlocked: 0, storage: 32 } , price: 10 }); 
        priceCase.create({ modelId: "A1453" , state: {state_body: 'cassé', state_screen: 'cassé', simBlocked: 0, storage: 64 } , price: 10 }); 

        //-------------
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 2,storage : 128} , price: 10 });;
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1549" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 2,storage : 128}, price: 10 });


        // ----------- 

        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1522" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 2,storage : 128}, price: 10 });
        // ---------------- 

        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "comme_neuf",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "bonne_état",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "abimé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "comme_neuf",state_screen : "cassé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "comme_neuf",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "bonne_état",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "abimé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "bonne_état",state_screen : "cassé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "comme_neuf",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "bonne_état",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "abimé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "abimé",state_screen : "cassé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "comme_neuf",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "bonne_état",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "abimé",simBlocked : 2,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 1,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 1,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 1,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 1,storage : 128} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 2,storage : 16} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 2,storage : 32} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 2,storage : 64} , price: 10 });
        priceCase.create({ modelId: "A1634" , state: {state_body: "cassé",state_screen : "cassé",simBlocked : 2,storage : 128}, price: 10 });
        // -------------
    }
}